---
# noqa: var-naming[no-role-prefix]

foreman_content_credentials_redhat9: []


foreman_products_redhat9:
  - name: Red Hat Enterprise Linux for x86_64
    organization: "{{ foreman_organization_redhat9 }}"
    repository_sets:
      # Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9
      - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)
        # basearch: noarch
        releasever: '9'
        # label: rhel-9-for-x86_64-baseos-rpms
        organization: "{{ foreman_organization_redhat9 }}"
      # Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9
      - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)
        # basearch: noarch
        releasever: '9'
        # label: rhel-9-for-x86_64-appstream-rpms
        organization: "{{ foreman_organization_redhat9 }}"
      # Red Hat Enterprise Linux 9 for x86_64 - Supplementary RPMs 9
      - name: Red Hat Enterprise Linux 9 for x86_64 - Supplementary (RPMs)
        # basearch: noarch
        releasever: '9'
        # label: rhel-9-for-x86_64-supplementary-rpms
        organization: "{{ foreman_organization_redhat9 }}"

      # Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs
      - name: Red Hat Satellite Client 6 for RHEL 9 x86_64 (RPMs)
        # basearch: noarch
        # label: satellite-client-6-for-rhel-9-x86_64-rpms
        organization: "{{ foreman_organization_redhat9 }}"


foreman_content_views_redhat9:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel9_baseos"
    organization: "{{ foreman_organization_redhat9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9"
        product: "{{ foreman_product_name_prefix | default('') }}'Red Hat Enterprise Linux for x86_64'"
    allow_promote: "{{ foreman_cv_allow_promote_redhat9 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel9_appstream"
    organization: "{{ foreman_organization_redhat9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9"
        product: "{{ foreman_product_name_prefix | default('') }}'Red Hat Enterprise Linux for x86_64'"
    allow_promote: "{{ foreman_cv_allow_promote_redhat9 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel9_supplementary"
    organization: "{{ foreman_organization_redhat9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Red Hat Enterprise Linux 9 for x86_64 - Supplementary RPMs 9"
        product: "{{ foreman_product_name_prefix | default('') }}'Red Hat Enterprise Linux for x86_64'"
    allow_promote: "{{ foreman_cv_allow_promote_redhat9 }}"

  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel9_sat_client_6"
    organization: "{{ foreman_organization_redhat9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs"
        product: "{{ foreman_product_name_prefix | default('') }}'Red Hat Enterprise Linux for x86_64'"
    allow_promote: "{{ foreman_cv_allow_promote_redhat9 }}"

foreman_composite_content_views_redhat9:
  - name: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}rhel9"
    organization: "{{ foreman_organization_redhat9 }}"
    composite: True
    allow_promote: "{{ foreman_ccv_allow_promote_redhat9 }}"
    auto_publish: "{{ foreman_ccv_auto_publish_redhat9 }}"
    components:
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel9_baseos"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel9_appstream"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel9_supplementary"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel9_sat_client_6"
        latest: true


foreman_operatingsystems_defaults: &foreman_operatingsystems_defaults
  os_family: "Redhat"
  password_hash: "SHA512"
  architectures:
    - x86_64
  # ptables:
  #   - Kickstart default
  #   - Kickstart custom
  ptables: "{{
    [ 'Kickstart default',
      'Kickstart custom' ] |
      union( foreman_partition_tables | default([]) | selectattr('os_family', 'defined') | selectattr('os_family', '==', 'Redhat') | map(attribute='name') | list )
    }}"


foreman_operatingsystems_redhat9:
  - name: "RedHat"
    major: "9"
    minor: "0"
    description: "RHEL 9.0"
    default_templates: "{{ foreman_operatingsystems_redhat90_default_templates | default( foreman_operatingsystems_redhat9_default_templates | default( foreman_operatingsystems_redhat_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) ) }}"
    <<: *foreman_operatingsystems_defaults
  - name: "RedHat"
    major: "9"
    minor: "1"
    description: "RHEL 9.1"
    default_templates: "{{ foreman_operatingsystems_redhat91_default_templates | default( foreman_operatingsystems_redhat9_default_templates | default( foreman_operatingsystems_redhat_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) ) }}"
    <<: *foreman_operatingsystems_defaults
  - name: "RedHat"
    major: "9"
    minor: "2"
    description: "RHEL 9.2"
    default_templates: "{{ foreman_operatingsystems_redhat92_default_templates | default( foreman_operatingsystems_redhat9_default_templates | default( foreman_operatingsystems_redhat_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) ) }}"
    <<: *foreman_operatingsystems_defaults
  - name: "RedHat"
    major: "9"
    minor: "3"
    description: "RHEL 9.3"
    default_templates: "{{ foreman_operatingsystems_redhat93_default_templates | default( foreman_operatingsystems_redhat9_default_templates | default( foreman_operatingsystems_redhat_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) ) }}"
    <<: *foreman_operatingsystems_defaults
  - name: "RedHat"
    major: "9"
    minor: "4"
    description: "RHEL 9.4"
    default_templates: "{{ foreman_operatingsystems_redhat94_default_templates | default( foreman_operatingsystems_redhat9_default_templates | default( foreman_operatingsystems_redhat_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) ) }}"
    <<: *foreman_operatingsystems_defaults
  - name: "RedHat"
    major: "9"
    minor: ""
    description: "RHEL 9"
    default_templates: "{{ foreman_operatingsystems_redhat9_default_templates | default( foreman_operatingsystems_redhat_default_templates | default( foreman_operatingsystems_el_default_templates | default([]) ) ) }}"
    <<: *foreman_operatingsystems_defaults


foreman_installation_media_defaults: &foreman_installation_media_defaults
  os_family: Redhat
  # organizations:
  #   - "{{ foreman_organization }}"
  # locations:
  #   - "{{ foreman_default_location }}"
  organizations: "{{ foreman_all_organizations_namelist }}"
  locations: "{{ foreman_all_locations_namelist }}"


foreman_installation_media_redhat9: []
# ENABLED IN VERSIONS!
#   - name: RHEL 9.3 BaseOS
#     path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/content/dist/rhel9/9.3/x86_64/baseos/kickstart/"
#     <<: *foreman_installation_media_defaults
#     operatingsystems:
#       - RHEL 9.3
#       - RHEL 9
#   - name: RHEL 9.3 AppStream
#     path: "https://{{ foreman_server_hostname }}/pulp/content/{{ foreman_organization }}/Library/content/dist/rhel9/9.3/x86_64/appstream/kickstart/"
#     <<: *foreman_installation_media_defaults
#     operatingsystems:
#       - RHEL 9.3
#       - RHEL 9


# Refer to https://access.redhat.com/solutions/125873 for pool ids
foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  # lifecycle_environment: "Library"
  # subscriptions:
  #   # Example to uyse a pool id
  #   # - pool_id: "8a88e9826db22df5016dd018abdd029b"
  #   # - name: "Red Hat Ansible Engine"
  #   # - name: "Red Hat Ansible Automation Platform"
  #   # - name: "Red Hat Enterprise Linux for x86_64"
  #   - name: "Red Hat Enterprise Linux Server"
  #   # - name: "Red Hat Satellite"
  #   # - name: "Red Hat Satellite Capsule"
  #   # - name: "Red Hat Software Collections (for RHEL Server)"
  #   # - name: "Red Hat OpenShift Container Platform"
  #   - name: "Extra Packages for Enterprise Linux"
  #   # - name: "Foreman"
  auto_attach: False
  release_version: 7Server
  # service_level: Standard


foreman_activation_keys_defaults_el9: &foreman_activation_keys_defaults_el9
  <<: *foreman_activation_keys_defaults
  # subscriptions:
  #   - name: "Red Hat Enterprise Linux for x86_64"
  #   - name: "Extra Packages for Enterprise Linux"
  release_version: 9


foreman_activation_keys_redhat9:
  - name: "{{ foreman_ak_prefix | default('ak_') }}{{ foreman_ak_name_prefix | default('') }}rhel9"
    organization: "{{ foreman_organization_redhat9 }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}rhel9"
    <<: *foreman_activation_keys_defaults_el9
    content_overrides:
      - label: rhel-9-for-x86_64-baseos-rpms
        override: default
      - label: rhel-9-for-x86_64-appstream-rpms
        override: default
      - label: rhel-9-for-x86_64-supplementary-rpms
        override: default
      - label: satellite-client-6-for-rhel-9-x86_64-rpms
        override: default


foreman_sync_plan_products_redhat9:
  - Red Hat Enterprise Linux for x86_64

